# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
